FROM node:16

RUN yarn
COPY ./front-end .
RUN yarn build


FROM nginx:latest
COPY /front-end/nginx.conf /etc/nginx/conf.d
COPY --from=dist /app/build /usr/share/nginx/html

ENTRYPOINT ["nginx", "-g", "daemon off;"]


