FROM node:16 as builder

WORKDIR /usr/src/app
COPY package.json .
COPY yarn.lock .

RUN yarn
COPY . .
RUN yarn build

FROM nginx
RUN rm -rf /etc/nginx/conf.d
COPY nginx.conf /etc/nginx/conf.d/nginx.conf
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]
