spring:
  datasource:
    url: jdbc:mysql://localhost:3306/secondhand-db
    username: root
    password: 1122
    hikari:
      maximum-pool-size: 10  # 커넥션 풀의 최대 크기 설정
      minimum-idle: 5  # 유휴 커넥션을 유지할 최소한의 커넥션 수 설정
      idle-timeout: 600000  # 유휴 커넥션의 최대 유지 시간 설정 (ms)
      pool-name: LabelingPool  # 커넥션 풀의 이름 설정
      validation-timeout: 5000  # 커넥션 유효성 검사 타임아웃 설정 (ms)
      auto-commit: true  # 자동 커밋 모드 설정
  cache:
    type: redis
    redis:
      time-to-live: 3600
      cache-null-values: true
      host: localhost
      port: 6379
  data:
    mongodb:
      uri: mongodb://localhost:27017/secondhand
  jpa:
    properties:
      hibernate:
#        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update # 데이터베이스 스키마 자동 업데이트 설정 (옵션)
logging:
  level:
    root: warn
    com.team5.secondhand: debug
  file:
    name: application.log
  logback:
    rolling policy:
      file-name-pattern: application.%d{yyyy-MM-dd}.log
      max-history: 30
server:
  address:
    frontend: "http://localhost:5173"
