-- MySQL Script generated by MySQL Workbench
-- Thu Jun  8 21:22:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema secondhand-db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `secondhand-db`;

-- -----------------------------------------------------
-- Schema secondhand-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `secondhand-db` DEFAULT CHARACTER SET utf8mb4;
USE `secondhand-db`;

-- -----------------------------------------------------
-- Table `secondhand-db`.`region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `secondhand-db`.`region`;

CREATE TABLE IF NOT EXISTS `secondhand-db`.`region`
(
    `id`       BIGINT      NOT NULL,
    `city`     VARCHAR(45) NOT NULL,
    `county`   VARCHAR(45) NOT NULL,
    `district` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secondhand-db`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `secondhand-db`.`member`;

CREATE TABLE IF NOT EXISTS `secondhand-db`.`member`
(
    `id`              BIGINT       NOT NULL AUTO_INCREMENT,
    `memberId`        VARCHAR(16)  NOT NULL,
    `profile_img_url` VARCHAR(100) NULL,
    `base_region`     BIGINT       NOT NULL,
    `sub_region`      BIGINT       NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `memberId_UNIQUE` (`memberId` ASC) VISIBLE,
    INDEX `fk_member_region1_idx` (`base_region` ASC) VISIBLE,
    INDEX `fk_member_region2_idx` (`sub_region` ASC) VISIBLE,
    CONSTRAINT `fk_member_region1`
        FOREIGN KEY (`base_region`)
            REFERENCES `secondhand-db`.`region` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_member_region2`
        FOREIGN KEY (`sub_region`)
            REFERENCES `secondhand-db`.`region` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secondhand-db`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `secondhand-db`.`category`;

CREATE TABLE IF NOT EXISTS `secondhand-db`.`category`
(
    `id`      BIGINT       NOT NULL,
    `title`   VARCHAR(16)  NOT NULL,
    `img_url` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secondhand-db`.`item_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `secondhand-db`.`item_image`;

CREATE TABLE IF NOT EXISTS `secondhand-db`.`item_image`
(
    `id`      BIGINT       NOT NULL,
    `image1`  VARCHAR(100) NOT NULL,
    `image2`  VARCHAR(100) NULL,
    `image3`  VARCHAR(100) NULL,
    `image4`  VARCHAR(100) NULL,
    `image5`  VARCHAR(100) NULL,
    `image6`  VARCHAR(100) NULL,
    `image7`  VARCHAR(100) NULL,
    `image8`  VARCHAR(100) NULL,
    `image9`  VARCHAR(100) NULL,
    `image10` VARCHAR(100) NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secondhand-db`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `secondhand-db`.`item`;

CREATE TABLE IF NOT EXISTS `secondhand-db`.`item`
(
    `id`            BIGINT       NOT NULL,
    `title`         VARCHAR(45)  NOT NULL,
    `contents`      TEXT         NOT NULL,
    `price`         INT          NULL,
    `status`        VARCHAR(16)  NULL,
    `thumbnail_url` VARCHAR(100) NULL,
    `hits`          INT          NULL DEFAULT 0,
    `chat_count`    INT          NULL,
    `like_count`    INT          NULL,
    `created_at`    DATETIME     NULL,
    `updated_at`    DATETIME     NULL,
    `seller_id`     BIGINT       NOT NULL,
    `category_id`   BIGINT       NOT NULL,
    `item_images`   BIGINT       NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_item_member_idx` (`seller_id` ASC) VISIBLE,
    INDEX `fk_item_category1_idx` (`category_id` ASC) VISIBLE,
    INDEX `fk_item_item_image1_idx` (`item_images` ASC) VISIBLE,
    CONSTRAINT `fk_item_member`
        FOREIGN KEY (`seller_id`)
            REFERENCES `secondhand-db`.`member` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_item_category1`
        FOREIGN KEY (`category_id`)
            REFERENCES `secondhand-db`.`category` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_item_item_image1`
        FOREIGN KEY (`item_images`)
            REFERENCES `secondhand-db`.`item_image` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secondhand-db`.`member_like_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `secondhand-db`.`member_like_item`;

CREATE TABLE IF NOT EXISTS `secondhand-db`.`member_like_item`
(
    `id`         BIGINT   NOT NULL,
    `member_id`  BIGINT   NOT NULL,
    `item_id`    BIGINT   NOT NULL,
    `created_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_member_has_item_item1_idx` (`item_id` ASC) VISIBLE,
    INDEX `fk_member_has_item_member1_idx` (`member_id` ASC) VISIBLE,
    CONSTRAINT `fk_member_has_item_member1`
        FOREIGN KEY (`member_id`)
            REFERENCES `secondhand-db`.`member` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_member_has_item_item1`
        FOREIGN KEY (`item_id`)
            REFERENCES `secondhand-db`.`item` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secondhand-db`.`member_chat_about_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `secondhand-db`.`member_chat_about_item`;

CREATE TABLE IF NOT EXISTS `secondhand-db`.`member_chat_about_item`
(
    `id`                  BIGINT   NOT NULL,
    `item_id`             BIGINT   NOT NULL,
    `buyer_id`            BIGINT   NOT NULL,
    `buyer_updated_at`    DATETIME NULL,
    `buyer_unread_count`  INT      NULL,
    `seller_updated_at`   DATETIME NULL,
    `seller_unread_count` INT      NULL,
    `created_at`          DATETIME NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_item_has_member_member1_idx` (`buyer_id` ASC) VISIBLE,
    INDEX `fk_item_has_member_item1_idx` (`item_id` ASC) VISIBLE,
    CONSTRAINT `fk_item_has_member_item1`
        FOREIGN KEY (`item_id`)
            REFERENCES `secondhand-db`.`item` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_item_has_member_member1`
        FOREIGN KEY (`buyer_id`)
            REFERENCES `secondhand-db`.`member` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
